version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=ebookdb
      - POSTGRES_USER=dev_test
      - POSTGRES_PASSWORD=devpostgres
    ports:
      ['5432:5432']
    volumes:
      [./postgres_data:/var/lib/postgresql]